apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: broken
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/this-org-does-not-exist/nope.git
        revision: HEAD
        directories:
          - path: 'envs/*'
  template:
    metadata:
      name: 'broken-{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/this-org-does-not-exist/nope.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: broken
