apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache
spec:
  serviceName: cache
  replicas: 1
  selector:
    matchLabels: 
      app: cache
  template:
    metadata:
      labels: 
        app: cache
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          resources:
            requests: 
              cpu: 10m
              memory: 16Mi