apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        env: prod
    spec:
      containers:
        - name: web
          image: nginx:1.27
          ports:
            - containerPort: 80
